# Generated by Django 2.2.4 on 2019-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allhelping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajudado',
            name='telefone',
            field=models.CharField(default='n/d', max_length=255, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
